### ISSUE TITLE
Implementação do Tracing

### ISSUE THREAD

**Issue by marcions** [mikemajesty/nestjs-microservice-boilerplate-api#11]
Olá Mike, primeiramente parabéns pelo excelente projeto. Estou fazendo alguns testes com o objetivo de entender o funcionamento e percebi, durante os testes, que não está sendo feito o registro do tracing no Zipkin. Essa implementação está funcional?

**Comment by mikemajesty** [comment]
@marcions obrigado, é para estar funcional, sim. 
![image](https://github.com/mikemajesty/nestjs-microservice-boilerplate-api/assets/11630212/81fcb56d-4385-4caf-b3dc-af9f17a5f4da)

tenta ajusta o horario da consulta, pode ser que o horario está meio errado.

**Comment by marcions** [comment]
Testei na master e funcionou, mas na branch feat/no-replica-set não funcionou
