### ISSUE TITLE
Mongo Connection doest not work

### ISSUE THREAD

**Issue by victorsoto91** [mikemajesty/nestjs-microservice-boilerplate-api#2]
I can't connect to mongo after initialize project.
`yarn start:dev`
![image](https://user-images.githubusercontent.com/121577217/230920082-5ff07910-3878-4ccb-8594-c29735acfb86.png)

**Comment by victorsoto91** [comment]
> Did you run "yarn infra" before?

Yeah, I run "yarn infra", docker compose works well and this is an screenshoot about services:
![image](https://user-images.githubusercontent.com/121577217/231000303-aea4d255-397c-4610-8f6a-b180e4870bff.png)

**Comment by mikemajesty** [comment]
Its seems a problem with replicaset, I have not a Mac to fix. If you fiz send a pull request
